from config.config_reader import config
breakfastEntreeItem_config = config.get_breakfastEntreeItem_config()

orderWindow = {
    "Drive-Thru" : {"auto_id":"ComboBox_CheckTypeSelector"},
    "hamburgerMenu" : {"auto_id":"RegisterPage_AppBar_Show_Button"},
    "Claim/Close Till" : {"title":"Claim/Close Till"},
    "Show Open Checks" : {"title":"Show Open Checks"},
    "searchClosedChecksButton" : {"title":"Search Closed Checks"},
    "moreButton" : {"title":"More"},
    "Till Device Selection" : {"title":"Till Device Selection"},
    "reconcileButton" : {"title":"Reconcile"},
    "Till, Successfully Claimed!" : {"title":"Till, Successfully Claimed!"},
    "claimButton" : {"title":"Claim"},
    "current cash" : {"title":"Current cash"},
    "close" : {"title":"", "auto_id":"TillDeviceSelectionView_Close_Button"},
    "breakfastButton" : {"title":"Breakfast        #21-29"},
    "entreeOnlyOption": {"title":"ENTREE ONLY"},
    "subTotalAmount" : {"auto_id":"CheckView_Subtotal_TextBlock"},
    "tax" : {"auto_id":"CheckView_Tax_Value"},
    "totalAmount" : {"auto_id":"CheckView_Total_TextBlock"},
    "Payment" : {"title" : "Payment"},
    "ROUND UP DONATION" : {"title" : "ROUND UP DONATION"},
    "NO THANKS" : {"title":"NO THANKS", "auto_id":"NoThanks", "control_type":"Button"},
    "okButton" : {"title": "OK"},
    "checkClosedText" : {"title": "Check Closed!"},
    "noCheckText" : {"title" : "No\nCheck", "auto_id" : "CheckView_NoCheck_Text", "control_type" : "Text"},
    "autoIdOfBreakfastEntreeItem": breakfastEntreeItem_config['autoIdOfBreakfastEntreeItem'],
    "breakfastEntreeItem" : {"title" : breakfastEntreeItem_config['breakfastEntreeItem']},
    "breakfastEntreeItemInCart": {"title": breakfastEntreeItem_config['breakfastEntreeItemCartView'], "auto_id":"CheckItemText_Item-0-47587-47958-48058", "control_type":"Text"},
    "SAUSAGE CROISSANT" : {"title": "SAUSAGE CROISSANT"},
    "#22 SAUSAGE CROISSANT" : {"title": "#22 SAUSAGE CROISSANT"},
    "SHELL EGG" : {"auto_id" : "DecrementQty_47587-47958-48058-56869-56646"},
    "modifiersInCart" : {"auto_id": "CheckItemDetail_Item-0-47587-47958-48058"},
    "MAYO": {"title": "MAYO"},
    "JALAPENOS" : {"title": "JALAPENOS"},
    "autoIdOfJALAPENOS" : "47587-47958-48058-56286-47810",
    "Logout" : {"title":"Logout"},
    "Drinks" : {"title": "DRINKS"},
    "Soft drinks" : {"title":"Soft drinks"},
    "Coffee" : {"title":"Coffee"},
    "HOT COFFEE" : {"title": "HOT COFFEE"},
    "Regular" : {"title":"Regular"},
    "Large" : {"title":"Large"},
    "Medium" : {"title":"Medium"},
    "FOUNTAIN DRINK" : {"title":"FOUNTAIN DRINK"},
    "autoIdOfLargeHotCoffee" : "47587-56634-48037-49678-47743-805",
    "autoIdOfFountainDrink" : "47587-56634-48037-49678-47753",
    "upChargeAmountInCart" : {"auto_id":"CheckItemDetail_Item-0-47587-56634-48037"},
    "COCA-COLA" : {"title":"COCA-COLA"},
    "DIET COKE" : {"title":"DIET COKE"},
    "closeItem" : {"auto_id":"TrashIconButton",},
    "ItemInCart" : {"auto_id":"CheckItemPrice_Item-0-47587-56634-48037"},
    "Sides" : {"title": "SIDES"},
    "autoIdOfFrenchFries" : "47587-56634-48037-49677-47718",
    "FRENCH FRIES" : {"title":"FRENCH FRIES"},
    "Fries" : {"title": "Fries"},
    "autoIdOfLargeFrenchFries" : "47587-56634-48037-49677-47718-805",
    "1 EGG ROLL" : {"title": "1 EGG ROLL"},
    "3 EGG ROLLS" : {"title": "3 EGG ROLLS"},
    "shrinkEGGROLL" : {"title":"3 EGG ROLLS", "auto_id":"TitleTextBlock"},
    "autoIdOfThreeEggRolls" : "47587-56634-48037-49677-47695",
    "shrinkFOUNTAINDRINK" : {"title":"FOUNTAIN DRINK", "auto_id":"TitleTextBlock"}
}
